use crate::P2PSwarm;
use crate::protocol::VideoStreamChunk;
use anyhow::Result;
use async_channel::{Receiver, Sender};
use async_trait::async_trait;
use futures::{AsyncReadExt, AsyncWriteExt, StreamExt};
use libp2p::gossipsub::{self, Event as GossipsubEvent, IdentTopic, MessageAuthenticity};
use libp2p::mdns;
use libp2p::swarm::{NetworkBehaviour, SwarmEvent};
use libp2p::{Multiaddr, PeerId, identity};
use libp2p_stream as stream;
use log::{info, warn};
use serde::{Deserialize, Serialize};
use serde_cbor;
use std::collections::HashMap;
use std::env;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, RwLock};
use std::time::{SystemTime, UNIX_EPOCH};

const STREAM_PROTOCOL_STR: &str = "/stream";
const STREAM_PROTOCOL: libp2p::StreamProtocol = libp2p::StreamProtocol::new(STREAM_PROTOCOL_STR);

/// Hybrid: gossipsub for announcements, stream for actual chunk transfer.
pub struct HybridP2P {
    inbound_rx: Receiver<VideoStreamChunk>,
    outbound_tx: Sender<VideoStreamChunk>,
}

#[derive(NetworkBehaviour)]
pub struct HybridBehaviour {
    mdns: mdns::tokio::Behaviour,
    gossipsub: gossipsub::Behaviour,
    stream: stream::Behaviour,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
struct Announcement {
    id: Vec<u8>,    // opaque id bytes - generated by originator
    timestamp: i64, // unix seconds when announced
}

#[derive(Serialize, Deserialize, Clone, Debug)]
struct Request {
    id: Vec<u8>,
}

impl HybridP2P {
    /// Run hybrid swarm: gossipsub for announcements + stream for transfers.
    pub async fn run(topic: &str) -> Result<Self> {
        // Identity
        let local_key = identity::Keypair::generate_ed25519();
        let local_peer_id = PeerId::from(local_key.public());
        info!("Local peer id: {local_peer_id}");

        // Configure gossipsub
        let gossipsub_config = gossipsub::ConfigBuilder::default()
            .validation_mode(gossipsub::ValidationMode::Strict)
            .build()
            .expect("valid gossipsub config");

        let mut gs = gossipsub::Behaviour::new(
            MessageAuthenticity::Signed(local_key.clone()),
            gossipsub_config,
        )
        .unwrap();

        // Subscribe topic for announcements
        let topic_ident = IdentTopic::new(topic.to_string());
        gs.subscribe(&topic_ident)?;

        // Behaviour (mDNS + Gossipsub + Stream)
        let behaviour = HybridBehaviour {
            mdns: mdns::tokio::Behaviour::new(mdns::Config::default(), local_peer_id)?,
            gossipsub: gs,
            stream: stream::Behaviour::new(),
        };

        // Control handles for stream behaviour (open/accept)
        let control = behaviour.stream.new_control();
        let mut control_accept = control.clone();
        let mut control_for_request = control.clone();

        // Build Swarm (Tokio + QUIC)
        let mut swarm = libp2p::SwarmBuilder::with_existing_identity(local_key)
            .with_tokio()
            .with_quic()
            .with_behaviour(|_| Ok(behaviour))?
            .build();

        // Listen on all interfaces, random UDP port via QUIC v1
        let addr: Multiaddr = "/ip4/0.0.0.0/udp/0/quic-v1"
            .parse()
            .expect("valid listen addr");
        swarm.listen_on(addr)?;

        // Channels for inbound/outbound chunks
        let (inbound_tx, inbound_rx) = async_channel::unbounded::<VideoStreamChunk>();
        let (outbound_tx, outbound_rx) = async_channel::unbounded::<VideoStreamChunk>();

        // Local storage of full chunk bytes keyed by announcement id
        let storage: Arc<RwLock<HashMap<Vec<u8>, Vec<u8>>>> = Arc::new(RwLock::new(HashMap::new()));

        // Counter for generating unique ids (combined with peer id + timestamp)
        let id_counter = Arc::new(AtomicU64::new(0));

        // BUFFER_TIME from env (seconds). Default to 30 seconds if not present/invalid.
        // Increase default so slightly delayed announcements aren't ignored.
        let buffer_time_secs: i64 = env::var("BUFFER_TIME")
            .ok()
            .and_then(|v| v.parse::<i64>().ok())
            .unwrap_or(30);

        // Task: Accept incoming streams (requests or direct chunk pushes)
        {
            let inbound_tx = inbound_tx.clone();
            let storage = storage.clone();
            // clone id_counter for this task so the original can still be used later
            let id_counter = id_counter.clone();
            tokio::spawn(async move {
                match control_accept.accept(STREAM_PROTOCOL) {
                    Ok(mut incoming) => {
                        while let Some((peer, mut st)) = incoming.next().await {
                            let mut data = Vec::new();
                            if let Err(e) = st.read_to_end(&mut data).await {
                                warn!("Failed reading incoming stream from {peer}: {e:?}");
                                continue;
                            }

                            // Try decode as Request first
                            if let Ok(req) = serde_cbor::from_slice::<Request>(&data) {
                                // Lookup and respond with stored bytes (if present).
                                // Acquire the read lock only briefly and clone the bytes so the guard
                                // is dropped before we await on writing to the stream.
                                let chunk_bytes_opt = {
                                    let guard = storage.read().unwrap();
                                    guard.get(&req.id).cloned()
                                };
                                if let Some(chunk_bytes) = chunk_bytes_opt {
                                    // Write chunk bytes back on the same stream
                                    if let Err(e) = st.write_all(&chunk_bytes).await {
                                        warn!("Failed to write chunk response to {peer}: {e:?}");
                                    }
                                    // close so requester.read_to_end completes
                                    if let Err(e) = st.close().await {
                                        warn!("Failed to close response stream to {peer}: {e:?}");
                                    }
                                } else {
                                    warn!("Requested chunk id not found for {peer}");
                                }
                                continue;
                            }

                            // Otherwise, try decode full VideoStreamChunk
                            match serde_cbor::from_slice::<VideoStreamChunk>(&data) {
                                Ok(stream_chunk) => {
                                    // Store raw bytes keyed by an id we cannot reconstruct here.
                                    // Store best-effort: use current time + counter + peer id as heuristic key
                                    let now = SystemTime::now()
                                        .duration_since(UNIX_EPOCH)
                                        .unwrap()
                                        .as_secs()
                                        as i64;
                                    // use peer.to_bytes() (Vec<u8>) so the tuple is serializable
                                    let key = serde_cbor::to_vec(&(
                                        peer.to_bytes(),
                                        now,
                                        id_counter.fetch_add(1, Ordering::SeqCst),
                                    ))
                                    .unwrap_or_else(|_| vec![]);
                                    storage.write().unwrap().insert(key, data.clone());

                                    let _ = inbound_tx.send(stream_chunk).await;
                                }
                                Err(e) => {
                                    warn!(
                                        "Failed to decode incoming stream payload from {peer}: {e:?}"
                                    );
                                }
                            }
                        }
                    }
                    Err(e) => {
                        warn!("Failed to accept incoming streams: {e:?}");
                    }
                }
            });
        }

        // Task: Drive swarm: handle gossipsub announcements, mdns discovery, outbound publishes and requests
        {
            let storage = storage.clone();
            let id_counter = id_counter.clone();
            let inbound_tx = inbound_tx.clone();
            let topic_loop = topic_ident.clone();
            tokio::spawn(async move {
                let mut swarm = swarm;
                loop {
                    tokio::select! {
                        maybe = swarm.next() => {
                            match maybe {
                                Some(SwarmEvent::Behaviour(HybridBehaviourEvent::Gossipsub(
                                    GossipsubEvent::Message { propagation_source, message_id: _, message },
                                ))) => {
                                    // Try decode as Announcement
                                    if let Ok(ann) = serde_cbor::from_slice::<Announcement>(&message.data) {
                                        // Check BUFFER_TIME: download only if announcement is newer than now - buffer_time
                                        let now = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs() as i64;
                                        if ann.timestamp >= (now - buffer_time_secs) {
                                            // Prefer requesting from the immediate forwarder (propagation_source),
                                            // which is usually already connected. If that fails, fall back to the
                                            // original publisher (message.source) when present.
                                            let origin = message.source.unwrap_or(propagation_source);
                                            swarm.behaviour_mut().gossipsub.add_explicit_peer(&origin);

                                            let targets = if origin == propagation_source {
                                                vec![propagation_source]
                                            } else {
                                                vec![propagation_source, origin]
                                            };

                                            let mut requested = false;
                                            for target in targets {
                                                match control_for_request.open_stream(target, STREAM_PROTOCOL).await {
                                                    Ok(mut stream) => {
                                                        let req = Request { id: ann.id.clone() };
                                                        match serde_cbor::to_vec(&req) {
                                                            Ok(bytes) => {
                                                                // write the request and then shutdown the write-half so the
                                                                // responder can complete read_to_end and then reply.
                                                                if let Err(e) = stream.write_all(&bytes).await {
                                                                    warn!("Failed to write request to {target}: {e:?}");
                                                                    continue;
                                                                }
                                                                // close the write-half so the responder can complete read_to_end and then reply.
                                                                if let Err(e) = stream.close().await {
                                                                    warn!("Failed to close request stream to {target}: {e:?}");
                                                                    // even if close fails, attempt to read response
                                                                }

                                                                // Read response (the chunk bytes)
                                                                let mut resp = Vec::new();
                                                                if let Err(e) = stream.read_to_end(&mut resp).await {
                                                                    warn!("Failed to read chunk response from {target}: {e:?}");
                                                                    continue;
                                                                }
                                                                match serde_cbor::from_slice::<VideoStreamChunk>(&resp) {
                                                                    Ok(chunk) => {
                                                                        // store bytes under announced id
                                                                        storage.write().unwrap().insert(ann.id.clone(), resp.clone());
                                                                        let _ = inbound_tx.send(chunk).await;
                                                                        requested = true;
                                                                        break;
                                                                    }
                                                                    Err(e) => {
                                                                        warn!("Failed to decode chunk response from {target}: {e:?}");
                                                                        // try next target
                                                                        continue;
                                                                    }
                                                                }
                                                            }
                                                            Err(e) => {
                                                                warn!("Failed to encode request: {e:?}");
                                                                break;
                                                            }
                                                        }
                                                    }
                                                    Err(e) => {
                                                        warn!("Failed to open stream to {target}: {e:?}");
                                                        // try next target
                                                    }
                                                }
                                            }

                                            if !requested {
                                                warn!("Could not obtain chunk for announcement id (too few reachable targets)");
                                            }
                                         } else {
                                             // Announcement too old; ignore
                                         }
                                     } else {
                                         // Non-announcement gossipsub message: ignore
                                     }
                                }

                                Some(SwarmEvent::Behaviour(HybridBehaviourEvent::Mdns(mdns::Event::Discovered(list)))) => {
                                    for (peer, addr) in list {
                                        // Dial discovered peer and help gossipsub mesh
                                        if let Err(e) = swarm.dial(addr.clone()) {
                                            warn!("Failed to dial discovered peer {peer}: {e:?}");
                                        }
                                        swarm.behaviour_mut().gossipsub.add_explicit_peer(&peer);
                                    }
                                }

                                Some(SwarmEvent::Behaviour(HybridBehaviourEvent::Mdns(mdns::Event::Expired(list)))) => {
                                    for (peer, _addr) in list {
                                        swarm.behaviour_mut().gossipsub.remove_explicit_peer(&peer);
                                    }
                                }

                                Some(SwarmEvent::ConnectionEstablished { peer_id, .. }) => {
                                    info!("Connection established with {peer_id}");
                                }

                                Some(SwarmEvent::ConnectionClosed { peer_id, .. }) => {
                                    info!("Connection closed with {peer_id}");
                                }

                                Some(_other) => {
                                    // ignore
                                }

                                None => break,
                            }
                        }

                        // Outbound: announce new chunks (store bytes locally + publish Announcement)
                        msg = outbound_rx.recv() => {
                            match msg {
                                Ok(chunk) => {
                                    match serde_cbor::to_vec(&chunk) {
                                        Ok(bytes) => {
                                            // generate id as cbor of (local_peer_id, timestamp, counter)
                                            let now = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs() as i64;
                                            let counter = id_counter.fetch_add(1, Ordering::SeqCst);
                                            // use local_peer_id.to_bytes() so PeerId isn't directly serialized
                                            let id = match serde_cbor::to_vec(&(local_peer_id.clone().to_bytes(), now, counter)) {
                                                Ok(v) => v,
                                                Err(e) => {
                                                    warn!("Failed to generate chunk id: {e:?}");
                                                    continue;
                                                }
                                            };

                                            // store bytes keyed by id
                                            storage.write().unwrap().insert(id.clone(), bytes.clone());

                                            // create announcement and publish
                                            let ann = Announcement { id: id.clone(), timestamp: now };
                                            match serde_cbor::to_vec(&ann) {
                                                Ok(ann_bytes) => {
                                                    // publish multiple times quickly to improve propagation
                                                    for attempt in 1..=3 {
                                                        if let Err(e) = swarm.behaviour_mut().gossipsub.publish(topic_loop.clone(), ann_bytes.clone()) {
                                                            warn!("Failed to publish announcement (attempt {attempt}): {e:?}");
                                                        } else {
                                                            info!("Published announcement (attempt {attempt})");
                                                        }
                                                        if attempt < 3 {
                                                            // short pause between attempts (non-blocking)
                                                            tokio::time::sleep(std::time::Duration::from_millis(50)).await;
                                                        }
                                                    }
                                                }
                                                Err(e) => {
                                                    warn!("Failed to encode announcement: {e:?}");
                                                }
                                            }
                                        }
                                        Err(e) => {
                                            warn!("Failed to encode outbound chunk: {e:?}");
                                        }
                                    }
                                }
                                Err(_closed) => {
                                    // channel closed; continue driving swarm
                                }
                            }
                        }
                    }
                }
            });
        }

        Ok(Self {
            inbound_rx,
            outbound_tx,
        })
    }
}

#[async_trait]
impl P2PSwarm for HybridP2P {
    fn inbound_rx(&self) -> &Receiver<VideoStreamChunk> {
        &self.inbound_rx
    }

    async fn send_message(&mut self, chunk: VideoStreamChunk) {
        let _ = self.outbound_tx.send(chunk).await;
    }
}
