version: 1
script:
  - chmod +x stream_test
  - mkdir -p AppDir/usr/bin
  - mv stream_test AppDir/usr/bin
  - mkdir -p AppDir/usr/share/icons
  - which mksquashfs || apt install squashfs-tools
AppDir:
  path: ./AppDir
  app_info:
    id: eu.luxuride.stream-test
    name: stream_test
    version: 0.1.0
    exec: usr/bin/stream_test
    exec_args: $@

AppImage:
  arch: x86_64